# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: party.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='party.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bparty.proto\"!\n\x11KnockKnockRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x19\n\tOpenReply\x12\x0c\n\x04open\x18\x01 \x01(\t\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"$\n\x0eHiWelcomeReply\x12\x12\n\nhi_welcome\x18\x01 \x01(\t2`\n\x05Party\x12,\n\x08OpenDoor\x12\x12.KnockKnockRequest\x1a\n.OpenReply\"\x00\x12)\n\x05Hello\x12\r.HelloRequest\x1a\x0f.HiWelcomeReply\"\x00\x62\x06proto3'
)




_KNOCKKNOCKREQUEST = _descriptor.Descriptor(
  name='KnockKnockRequest',
  full_name='KnockKnockRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='KnockKnockRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=48,
)


_OPENREPLY = _descriptor.Descriptor(
  name='OpenReply',
  full_name='OpenReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='open', full_name='OpenReply.open', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=75,
)


_HELLOREQUEST = _descriptor.Descriptor(
  name='HelloRequest',
  full_name='HelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='HelloRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=105,
)


_HIWELCOMEREPLY = _descriptor.Descriptor(
  name='HiWelcomeReply',
  full_name='HiWelcomeReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hi_welcome', full_name='HiWelcomeReply.hi_welcome', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=143,
)

DESCRIPTOR.message_types_by_name['KnockKnockRequest'] = _KNOCKKNOCKREQUEST
DESCRIPTOR.message_types_by_name['OpenReply'] = _OPENREPLY
DESCRIPTOR.message_types_by_name['HelloRequest'] = _HELLOREQUEST
DESCRIPTOR.message_types_by_name['HiWelcomeReply'] = _HIWELCOMEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KnockKnockRequest = _reflection.GeneratedProtocolMessageType('KnockKnockRequest', (_message.Message,), {
  'DESCRIPTOR' : _KNOCKKNOCKREQUEST,
  '__module__' : 'party_pb2'
  # @@protoc_insertion_point(class_scope:KnockKnockRequest)
  })
_sym_db.RegisterMessage(KnockKnockRequest)

OpenReply = _reflection.GeneratedProtocolMessageType('OpenReply', (_message.Message,), {
  'DESCRIPTOR' : _OPENREPLY,
  '__module__' : 'party_pb2'
  # @@protoc_insertion_point(class_scope:OpenReply)
  })
_sym_db.RegisterMessage(OpenReply)

HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'party_pb2'
  # @@protoc_insertion_point(class_scope:HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HiWelcomeReply = _reflection.GeneratedProtocolMessageType('HiWelcomeReply', (_message.Message,), {
  'DESCRIPTOR' : _HIWELCOMEREPLY,
  '__module__' : 'party_pb2'
  # @@protoc_insertion_point(class_scope:HiWelcomeReply)
  })
_sym_db.RegisterMessage(HiWelcomeReply)



_PARTY = _descriptor.ServiceDescriptor(
  name='Party',
  full_name='Party',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=145,
  serialized_end=241,
  methods=[
  _descriptor.MethodDescriptor(
    name='OpenDoor',
    full_name='Party.OpenDoor',
    index=0,
    containing_service=None,
    input_type=_KNOCKKNOCKREQUEST,
    output_type=_OPENREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Hello',
    full_name='Party.Hello',
    index=1,
    containing_service=None,
    input_type=_HELLOREQUEST,
    output_type=_HIWELCOMEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PARTY)

DESCRIPTOR.services_by_name['Party'] = _PARTY

# @@protoc_insertion_point(module_scope)
